<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceContainer name="content">
            <block class="Custom\Loyalitypoints\Block\Adminhtml\Rewards\Grid" name="custom_loyalty_points_rewards" template="Custom_Loyalitypoints::grid.phtml"/>
        </referenceContainer>
    </body>
</page>
